name: anri
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  local_auth: ^2.2.0
  shared_preferences: ^2.2.3
  particles_flutter: ^0.1.4
  cupertino_icons: ^1.0.8
  intl: ^0.19.0 
  http: ^1.2.1 
  timeago: ^3.6.1
  flutter_html: ^3.0.0 
  flutter_dotenv: ^5.1.0 
  
  # --- BARU: Tambahkan provider di sini ---
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/anri_logo.png
    - assets/images/label-critical.png
    - assets/images/label-high.png
    - assets/images/label-medium.png
    - assets/images/label-low.png
    - .env